### ISSUE TITLE
A global approach to multi-axis swept mesh generation

### ISSUE THREAD

**Issue by xiaoyan16a** [cnr-isti-vclab/HexaLab#16]
DOI: https://doi.org/10.1016/j.proeng.2017.09.817

**Comment by xiaoyan16a** [comment]
[Uploading A global approach to multi-axis swept mesh generation.pdf…]()

**Comment by xiaoyan16a** [comment]
Link to the dataset: https://drive.google.com/open?id=1Qgouj0uzOvye_4XuJM1vORa-eXaiASxF

**Comment by mlivesu** [comment]
Thank you for sharing your data with us. I just sent a pull request to Paolo.

**Comment by cignoni** [comment]
Pull request merged. Thanks!
