### ISSUE TITLE
Error when loading large meshes

### ISSUE THREAD

**Issue by bbrrck** [cnr-isti-vclab/HexaLab#26]
HexaLab gets stuck at *Loading...* when I try to load some of the larger datasets (>10 MB), for instance [kiss_hex.mesh](https://github.com/cnr-isti-vclab/HexaLab/blob/master/datasets/2011%20-%20All-Hex%20Mesh%20Generation%20via%20Volumetric%20PolyCube%20Deformation/kiss_hex.mesh) (17.5 MB). Tested in Chrome and Firefox on two different machines, same thing happens every time.

Error:  
*Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 1073741824, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0*

[Full console output](https://github.com/cnr-isti-vclab/HexaLab/files/2817341/www.hexalab.net-1548941147122.log)

<img width="1672" alt="screenshot 2019-01-31 at 14 23 15" src="https://user-images.githubusercontent.com/5372742/52056929-ee35bd00-2563-11e9-9a2f-5aac1d2e6361.png">

**Comment by cignoni** [comment]
Sadly confirmed. 
Current Javascript environments are a bit limited in memory. Recompiling as suggested (-s ALLOW_MEMORY_GROWTH) does not help much and switch to a slower memory model. 
We plan to switch to more compact inner structure in a future.

**Comment by cignoni** [comment]
We are happy to announce that we (Marco Tarini actually) rewrote the core data structures and now it can load large meshes All the datasets now loads correctly! (even the one of 600k cells)
